Series

Uma Series é um objeto de tipo array unidimensional que contém uma
sequência de valores (de tipos semelhantes aos tipos do NumPy) de mesmo
tipo e um array associado com rótulos de dados chamado índice

In [47]:
import pandas as pd
import numpy as np

In [2]:
#declarando uma Series
obj =pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

Atributos de Series

In [5]:
#atributos
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
#Series com rótulos
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2["a"]

np.int64(-5)

In [11]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [12]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [14]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
"b" in obj2

True

In [18]:
"e" in obj2

False

In [19]:
#Criando uma serie pelo dicionario
sdata = {"Ohio":3500, "Texas":7100, "Oregon":1600, "Utah":5000}
obj3 = pd.Series(sdata)
obj3

Ohio      3500
Texas     7100
Oregon    1600
Utah      5000
dtype: int64

In [20]:
#Conversão de serie em dicionario
obj3.to_dict()

{'Ohio': 3500, 'Texas': 7100, 'Oregon': 1600, 'Utah': 5000}

In [21]:
#sobre escrevedno Keys do dicionario
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
dtype: float64

In [22]:
#valores ausestes,nulos
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [24]:
#alinhamento automático pelo rótulo do índice em aritméticas
obj3 + obj4

California        NaN
Ohio           7000.0
Oregon         3200.0
Texas         14200.0
Utah              NaN
dtype: float64

In [25]:
#colocando nome na coluna
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
Name: population, dtype: float64

In [27]:
#indice por atribuição
obj
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

Data Frame

Um DataFrame representa uma tabela de dados retangular e contém uma
coleção ordenada e nomeada de colunas, cada uma podendo ter um tipo de
valor diferente (numérico, string, booleano etc.).

In [8]:
#criando um dara frame atras de um dicionario de listas
data = {"state":["Ohio","Ohio", "Ohio","Nevada", "Nevada", "Nevada"],
        "year":[2000,2001,2002,2001, 2002, 2003],
        "pop": [1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [13]:
# mostra incio e fim
x =frame.head()
print(x)
print("_______")
y = frame.tail()
print(y)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
_______
    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [14]:
#colunas especificadas
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [16]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [17]:
#recuperação de series uma coluna dataframe
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [18]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [21]:
#acesso a atributos
frame2.loc[1] #eixo

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [23]:
frame2.iloc[2] #inteiros

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [26]:
#atribuição
frame2["debt"] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [29]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5  16.5     True
1  2001    Ohio  1.7  16.5     True
2  2002    Ohio  3.6  16.5     True
3  2001  Nevada  2.4  16.5    False
4  2002  Nevada  2.9  16.5    False
5  2003  Nevada  3.2  16.5    False

In [39]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [41]:
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [43]:
#transposição, troca linhas e colunas
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [45]:
#retorno bidimensional
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

Objetos Index

Os objetos Index do pandas são responsáveis por conter os rótulos dos eixos
(incluindo o nome das colunas de um DataFrame) e outros metadados (como
o nome ou os nomes dos eixos).

In [51]:
from numpy._core.defchararray import index
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int64

In [52]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [54]:
index[1:]

Index(['b', 'c'], dtype='object')

In [55]:
#objetos index são imutaveis
index[1] =  'd'

TypeError: Index does not support mutable operations