Series

Uma Series é um objeto de tipo array unidimensional que contém uma
sequência de valores (de tipos semelhantes aos tipos do NumPy) de mesmo
tipo e um array associado com rótulos de dados chamado índice

In [1]:
import pandas as pd
import numpy as np

In [2]:
#declarando uma Series
obj =pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

Atributos de Series

In [3]:
#atributos
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
#Series com rótulos
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2["a"]

np.int64(-5)

In [ ]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [8]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [9]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [10]:
"b" in obj2

True

In [11]:
"e" in obj2

False

In [12]:
#Criando uma serie pelo dicionario
sdata = {"Ohio":3500, "Texas":7100, "Oregon":1600, "Utah":5000}
obj3 = pd.Series(sdata)
obj3

Ohio      3500
Texas     7100
Oregon    1600
Utah      5000
dtype: int64

In [13]:
#Conversão de serie em dicionario
obj3.to_dict()

{'Ohio': 3500, 'Texas': 7100, 'Oregon': 1600, 'Utah': 5000}

In [14]:
#sobre escrevedno Keys do dicionario
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
dtype: float64

In [ ]:
#valores ausestes,nulos
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
#alinhamento automático pelo rótulo do índice em aritméticas
obj3 + obj4

California        NaN
Ohio           7000.0
Oregon         3200.0
Texas         14200.0
Utah              NaN
dtype: float64

In [ ]:
#colocando nome na coluna
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
Name: population, dtype: float64

In [ ]:
#indice por atribuição
obj
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

Data Frame

Um DataFrame representa uma tabela de dados retangular e contém uma
coleção ordenada e nomeada de colunas, cada uma podendo ter um tipo de
valor diferente (numérico, string, booleano etc.).

In [2]:
#criando um dara frame atras de um dicionario de listas
data = {"state":["Ohio","Ohio", "Ohio","Nevada", "Nevada", "Nevada"],
        "year":[2000,2001,2002,2001, 2002, 2003],
        "pop": [1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [3]:
# mostra incio e fim
x =frame.head()
print(x)
print("_______")
y = frame.tail()
print(y)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
_______
    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [4]:
#colunas especificadas
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [5]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [6]:
#recuperação de series uma coluna dataframe
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [7]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [8]:
#acesso a atributos
frame2.loc[1] #eixo

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [9]:
frame2.iloc[2] #inteiros

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [10]:
#atribuição
frame2["debt"] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [11]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5  16.5     True
1  2001    Ohio  1.7  16.5     True
2  2002    Ohio  3.6  16.5     True
3  2001  Nevada  2.4  16.5    False
4  2002  Nevada  2.9  16.5    False
5  2003  Nevada  3.2  16.5    False

In [12]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [13]:
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [14]:
#transposição, troca linhas e colunas
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [15]:
#retorno bidimensional
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

Objetos Index

Os objetos Index do pandas são responsáveis por conter os rótulos dos eixos
(incluindo o nome das colunas de um DataFrame) e outros metadados (como
o nome ou os nomes dos eixos).

In [16]:
from numpy._core.defchararray import index
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int64

In [17]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [18]:
index[1:]

Index(['b', 'c'], dtype='object')

In [19]:
#objetos index são imutaveis
index[1] =  'd'

TypeError: Index does not support mutable operations

Reindexação

In [2]:
#reindex novo objetos com valores organizados
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b","a","c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
#metodo method no reindex para preechimento
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [5]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [7]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])

frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [10]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

Remoção de entradas de um eixo

In [3]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [5]:
#reitar c
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [7]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [8]:
#drop linhas
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [9]:
#drop colunas
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [10]:
#drop colunas pasando axis=1
data.drop("two", axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

Indexação, seleção e filtragem

In [3]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [4]:
obj["b"]

np.float64(1.0)

In [5]:
obj[1]

/tmp/ipykernel_7534/2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

np.float64(1.0)

In [6]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [8]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [9]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [10]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False